(library
 (name earde)
 (public_name earde)
 (libraries
  dream
  dream-pure
  caqti
  caqti-lwt
  caqti-lwt.unix
  caqti-driver-postgresql
  argon2
  base64
  yojson
  logs
  unix
  lwt
  lwt.unix
  cohttp
  cohttp-lwt
  cohttp-lwt-unix
  uri
  digestif
  mtime.clock.os)
 (preprocess
  (pps lwt_ppx)))
